package com.example.engine.animation

import androidx.compose.ui.geometry.CornerRadius
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.drawscope.DrawScope
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.unit.dp
import com.example.controller.KinematicCharacterController
import com.example.engine.math.Vector2
import com.example.fsm.CharacterStateType
import kotlin.math.abs
import kotlin.math.max

/**
 * Live active combat hitbox generated by an animation frame event.
 */
data class ActiveHitboxInstance(
    var isActive: Boolean = false,
    var worldBoundsMinX: Float = 0f,
    var worldBoundsMinY: Float = 0f,
    var worldBoundsMaxX: Float = 0f,
    var worldBoundsMaxY: Float = 0f,
    var damage: Float = 0f,
    var baseKnockback: Float = 0f,
    var knockbackScaling: Float = 0f,
    var knockbackAngleDeg: Float = 0f,
    var hitStunFrames: Int = 0
)

/**
 * Historical trail slice for slashing arcs and dash afterimages.
 */
data class TrailPoint(
    var worldX: Float = 0f,
    var worldY: Float = 0f,
    var angleDeg: Float = 0f,
    var life: Float = 1.0f,
    var hexColor: String = "#FF4500"
)

/**
 * CharacterAnimationBridge Class:
 * Interfaces directly with the Kinematic Character Controller and Finite State Machine.
 * Solves hierarchical 2D skeletal transformation matrices (Forward Kinematics),
 * executes frame-perfect hitbox activation/deactivation windows, and coordinates
 * micro-animation transitions without frame drops or visual glitches.
 */
class CharacterAnimationBridge(
    val profile: AnimationDataProfile = AnimationDataProfile.createStandardFighterProfile("valkyrie")
) {

    // Current Animation State
    var currentAnimationId: AnimationId = AnimationId.IDLE
        private set
    var currentClip: AnimationClip = profile.clips[AnimationId.IDLE] ?: profile.clips.values.first()
        private set
    var currentFrame: Float = 0f
        private set
    var playbackSpeed: Float = 1.0f

    // Attack locking flag (prevents run/idle transitions from interrupting active attack keyframes)
    var isAttackLocked: Boolean = false
        private set

    // Skeletal Pose Buffers (zero runtime object allocation)
    private val localPoseTransforms: MutableMap<BoneId, BoneTransform> = mutableMapOf()
    private val worldMatrices: MutableMap<BoneId, AffineMatrix2D> = mutableMapOf()
    private val localMatrixScratch = AffineMatrix2D()

    // Combat Hitbox Registry
    val activeHitboxes: MutableList<ActiveHitboxInstance> = mutableListOf(ActiveHitboxInstance())

    // Visual Weapon Trail Pool
    private val maxTrailPoints = 12
    val trailPoints: Array<TrailPoint> = Array(maxTrailPoints) { TrailPoint() }
    var activeTrailHexColor: String? = null
        private set

    // Foot placement synchronization
    var footStepPhase: Float = 0f
        private set

    init {
        // Initialize all bone matrices
        for (bone in BoneId.values()) {
            localPoseTransforms[bone] = profile.defaultBindPose[bone]?.copy() ?: BoneTransform()
            worldMatrices[bone] = AffineMatrix2D()
        }
        recalculateSkeletalMatrices(0f, 0f, 1.0f)
    }

    /**
     * Fixed-physics tick update called at 60Hz from game simulation.
     */
    fun fixedUpdate(controller: KinematicCharacterController, dt: Float) {
        val state = controller.stateMachine.getCurrentStateType()
        val vel = controller.velocity
        val facingDir = controller.facingDirection
        val isGrounded = controller.isGrounded
        val stickX = controller.inputQueue.getStickX()
        val stickY = controller.inputQueue.getStickY()

        // 1. Synchronize Animation Clip with Kinematic FSM State
        syncWithFsmState(state, vel, facingDir, isGrounded, stickX, stickY, dt, controller.config.maxGroundSpeed)

        // 2. Advance discrete animation playback
        advancePlayback(dt, controller)

        // 3. Compute forward kinematics for all bones
        recalculateSkeletalMatrices(controller.position.x, controller.position.y, facingDir)

        // 4. Update visual trail decay
        updateTrails(dt)
    }

    /**
     * Synchronizes the 2D Animation State directly with the Kinematic FSM State.
     */
    fun syncWithFsmState(
        state: CharacterStateType,
        vel: Vector2,
        facingDir: Float,
        isGrounded: Boolean,
        stickX: Float,
        stickY: Float,
        dt: Float,
        groundMaxSpeed: Float
    ) {
        // Disrupted States immediately cancel attack locks
        if (state == CharacterStateType.HURT || state == CharacterStateType.KNOCKBACK) {
            isAttackLocked = false
            clearHitboxes()
            activeTrailHexColor = null

            val targetId = if (state == CharacterStateType.KNOCKBACK) AnimationId.KNOCKBACK else AnimationId.HITSTUN
            if (currentAnimationId != targetId) {
                transitionToClip(targetId, resetFrame = true)
            }
            playbackSpeed = 1.0f
            return
        }

        // If currently in an uninterruptible attack swing, let it finish its execution loop
        if (isAttackLocked) {
            return
        }

        // Map FSM states to specialized animation states
        when (state) {
            CharacterStateType.IDLE -> {
                if (currentAnimationId != AnimationId.IDLE) {
                    transitionToClip(AnimationId.IDLE, resetFrame = true)
                }
                playbackSpeed = 1.0f
            }

            CharacterStateType.RUN -> {
                if (currentAnimationId != AnimationId.RUN) {
                    transitionToClip(AnimationId.RUN, resetFrame = false)
                }
                // Looping with foot-placement speed modifiers
                val speedRatio = (abs(vel.x) / max(groundMaxSpeed, 1f)).coerceIn(0.4f, 1.8f)
                playbackSpeed = speedRatio
                footStepPhase = (footStepPhase + dt * speedRatio * 8f) % 1.0f
            }

            CharacterStateType.DASH -> {
                if (currentAnimationId != AnimationId.DASH) {
                    transitionToClip(AnimationId.DASH, resetFrame = true)
                }
                playbackSpeed = 1.0f
            }

            CharacterStateType.JUMP -> {
                // Physics-velocity dependent interpolation: Ascending vs Apex
                val target = if (vel.y < -200f) AnimationId.JUMP_RISE else AnimationId.JUMP_APEX
                if (currentAnimationId != target) {
                    transitionToClip(target, resetFrame = false)
                }
                playbackSpeed = 1.0f
            }

            CharacterStateType.FALL -> {
                if (currentAnimationId != AnimationId.FALL) {
                    transitionToClip(AnimationId.FALL, resetFrame = false)
                }
                playbackSpeed = 1.0f
            }

            CharacterStateType.WALL_CLING -> {
                if (currentAnimationId != AnimationId.WALL_CLING) {
                    transitionToClip(AnimationId.WALL_CLING, resetFrame = true)
                }
                playbackSpeed = 1.0f
            }

            CharacterStateType.WALL_SLIDE -> {
                if (currentAnimationId != AnimationId.WALL_SLIDE) {
                    transitionToClip(AnimationId.WALL_SLIDE, resetFrame = false)
                }
                playbackSpeed = 1.0f
            }

            else -> Unit
        }
    }

    /**
     * Manually triggers an attack animation (Neutral, Side, or Down) with strict frame-perfect locking.
     */
    fun triggerAttack(attackType: AnimationId): Boolean {
        if (isAttackLocked) return false
        val clip = profile.clips[attackType] ?: return false

        isAttackLocked = true
        transitionToClip(attackType, resetFrame = true)
        return true
    }

    /**
     * Switches active animation clip and resets playback counter.
     */
    fun transitionToClip(newId: AnimationId, resetFrame: Boolean = true) {
        val nextClip = profile.clips[newId] ?: return
        currentAnimationId = newId
        currentClip = nextClip
        if (resetFrame) {
            currentFrame = 0f
            clearHitboxes()
        }
    }

    /**
     * Advances playback frames and processes data-driven frame events.
     */
    private fun advancePlayback(dt: Float, controller: KinematicCharacterController) {
        val prevFrameInt = currentFrame.toInt()
        val frameAdvance = dt * currentClip.playbackFps * playbackSpeed
        currentFrame += frameAdvance

        val newFrameInt = currentFrame.toInt()

        // Check if clip finished
        if (currentFrame >= currentClip.totalFrames) {
            if (currentClip.isLooping) {
                currentFrame %= currentClip.totalFrames.toFloat()
            } else {
                currentFrame = (currentClip.totalFrames - 1).toFloat()
                if (isAttackLocked) {
                    isAttackLocked = false
                    clearHitboxes()
                    activeTrailHexColor = null
                    // Return to Idle or Fall depending on grounded state
                    val fallback = if (controller.isGrounded) AnimationId.IDLE else AnimationId.FALL
                    transitionToClip(fallback, resetFrame = true)
                }
            }
        }

        // Process discrete frame events in the interval [prevFrameInt, newFrameInt]
        evaluateEvents(prevFrameInt, newFrameInt, controller)

        // Sample current pose into local transforms
        currentClip.samplePose(currentFrame, localPoseTransforms)
    }

    /**
     * Reads data-driven event triggers for frame-perfect hitbox and VFX activation.
     */
    private fun evaluateEvents(fromFrame: Int, toFrame: Int, controller: KinematicCharacterController) {
        for (event in currentClip.events) {
            if (event.frame in fromFrame..toFrame) {
                when (event.type) {
                    AnimationEventType.HITBOX_ACTIVATE -> {
                        val def = event.hitbox
                        if (def != null) {
                            activateHitbox(def, controller.position.x, controller.position.y, controller.facingDirection)
                        }
                    }

                    AnimationEventType.HITBOX_DEACTIVATE -> {
                        clearHitboxes()
                    }

                    AnimationEventType.HURTBOX_DISABLE -> {
                        controller.setIsInvincibleManually(true)
                    }

                    AnimationEventType.HURTBOX_ENABLE -> {
                        controller.setIsInvincibleManually(false)
                    }

                    AnimationEventType.TRAIL_EFFECT_START -> {
                        activeTrailHexColor = event.hexColor ?: "#FF4500"
                    }

                    AnimationEventType.TRAIL_EFFECT_END -> {
                        activeTrailHexColor = null
                    }

                    else -> Unit
                }
            }
        }
    }

    private fun activateHitbox(def: HitboxDefinition, rootX: Float, rootY: Float, facingDir: Float) {
        val h = activeHitboxes[0]
        h.isActive = true
        val effectiveOffsetX = def.relativeX * facingDir
        val centerX = rootX + effectiveOffsetX
        val centerY = rootY + def.relativeY

        h.worldBoundsMinX = centerX - def.width * 0.5f
        h.worldBoundsMinY = centerY - def.height * 0.5f
        h.worldBoundsMaxX = centerX + def.width * 0.5f
        h.worldBoundsMaxY = centerY + def.height * 0.5f

        h.damage = def.damage
        h.baseKnockback = def.baseKnockback
        h.knockbackScaling = def.knockbackScaling
        h.knockbackAngleDeg = if (facingDir > 0f) def.knockbackAngleDeg else 180f - def.knockbackAngleDeg
        h.hitStunFrames = def.hitStunFrames
    }

    private fun clearHitboxes() {
        for (h in activeHitboxes) {
            h.isActive = false
        }
    }

    /**
     * Solves the forward kinematics tree from Root to leaves.
     */
    fun recalculateSkeletalMatrices(rootX: Float, rootY: Float, facingDir: Float) {
        val rootMatrix = worldMatrices.getOrPut(BoneId.ROOT) { AffineMatrix2D() }
        rootMatrix.setTRS(rootX, rootY, 0f, facingDir, 1.0f)

        // Traverse hierarchy in ordered layers
        for (bone in BoneId.values()) {
            if (bone == BoneId.ROOT) continue
            val parent = profile.boneHierarchy[bone] ?: BoneId.ROOT
            val parentMatrix = worldMatrices[parent] ?: rootMatrix

            val localTransform = localPoseTransforms[bone] ?: profile.defaultBindPose[bone] ?: BoneTransform()
            localMatrixScratch.setTRS(
                localTransform.tx,
                localTransform.ty,
                localTransform.rotationDegrees,
                localTransform.sx,
                localTransform.sy
            )

            val boneWorldMatrix = worldMatrices.getOrPut(bone) { AffineMatrix2D() }
            boneWorldMatrix.copyFrom(parentMatrix)
            boneWorldMatrix.multiply(localMatrixScratch)
        }

        // Spawn weapon trail slice if trail is active
        if (activeTrailHexColor != null) {
            val weaponMatrix = worldMatrices[BoneId.WEAPON_R]
            if (weaponMatrix != null) {
                spawnTrailPoint(weaponMatrix.m02, weaponMatrix.m12, activeTrailHexColor!!)
            }
        }
    }

    private fun spawnTrailPoint(x: Float, y: Float, hexColor: String) {
        for (tp in trailPoints) {
            if (tp.life <= 0f) {
                tp.worldX = x
                tp.worldY = y
                tp.life = 1.0f
                tp.hexColor = hexColor
                return
            }
        }
        // If full, overwrite index 0
        trailPoints[0].worldX = x
        trailPoints[0].worldY = y
        trailPoints[0].life = 1.0f
        trailPoints[0].hexColor = hexColor
    }

    private fun updateTrails(dt: Float) {
        for (tp in trailPoints) {
            if (tp.life > 0f) {
                tp.life -= dt * 4.5f
                if (tp.life < 0f) tp.life = 0f
            }
        }
    }

    fun getWorldBoneMatrix(bone: BoneId): AffineMatrix2D? = worldMatrices[bone]

    /**
     * Production Canvas Renderer:
     * Draws the 2D skeletal cutout parts sorted by explicit Z-Order.
     */
    fun render(
        drawScope: DrawScope,
        worldToScreen: (Float, Float) -> Offset,
        zoom: Float,
        themeColorArgb: Long,
        isInvincible: Boolean
    ) {
        // 1. Draw Visual Trails (slashing arcs)
        for (tp in trailPoints) {
            if (tp.life <= 0f) continue
            val screenPos = worldToScreen(tp.worldX, tp.worldY)
            val trailAlpha = tp.life * 0.7f
            val trailColor = try {
                Color(android.graphics.Color.parseColor(tp.hexColor)).copy(alpha = trailAlpha)
            } catch (_: Exception) {
                Color(0xFFFF4500).copy(alpha = trailAlpha)
            }

            drawScope.drawCircle(
                color = trailColor,
                radius = 16f * zoom * tp.life + 4f,
                center = screenPos
            )
        }

        // 2. Sort bones according to their designated cutout z-order
        val sortedBones = BoneId.values().sortedBy { profile.zOrderMap[it] ?: 0 }

        val baseColor = Color(themeColorArgb)
        val metalHighlight = Color(0xFFF8FAFC)
        val shadowColor = baseColor.copy(alpha = 0.55f)

        for (bone in sortedBones) {
            val matrix = worldMatrices[bone] ?: continue
            val screenPos = worldToScreen(matrix.m02, matrix.m12)

            when (bone) {
                BoneId.TORSO -> {
                    val w = 26f * zoom
                    val h = 34f * zoom
                    drawScope.drawRoundRect(
                        brush = Brush.verticalGradient(listOf(baseColor, Color(0xFF0F172A))),
                        topLeft = Offset(screenPos.x - w * 0.5f, screenPos.y - h * 0.5f),
                        size = Size(w, h),
                        cornerRadius = CornerRadius(6f * zoom)
                    )
                }

                BoneId.HEAD -> {
                    val r = 14f * zoom
                    drawScope.drawCircle(
                        color = baseColor,
                        radius = r,
                        center = screenPos
                    )
                    // Visor
                    drawScope.drawCircle(
                        color = Color(0xFF00FFCC),
                        radius = r * 0.45f,
                        center = Offset(screenPos.x + 3f * zoom, screenPos.y)
                    )
                }

                BoneId.UPPER_ARM_L, BoneId.UPPER_ARM_R -> {
                    val armLength = 16f * zoom
                    val endX = matrix.transformX(0f, 14f)
                    val endY = matrix.transformY(0f, 14f)
                    val endScreen = worldToScreen(endX, endY)
                    drawScope.drawLine(
                        color = if (bone == BoneId.UPPER_ARM_R) baseColor else shadowColor,
                        start = screenPos,
                        end = endScreen,
                        strokeWidth = 7f * zoom,
                        cap = StrokeCap.Round
                    )
                }

                BoneId.LOWER_ARM_L, BoneId.LOWER_ARM_R -> {
                    val endX = matrix.transformX(0f, 12f)
                    val endY = matrix.transformY(0f, 12f)
                    val endScreen = worldToScreen(endX, endY)
                    drawScope.drawLine(
                        color = if (bone == BoneId.LOWER_ARM_R) metalHighlight else shadowColor,
                        start = screenPos,
                        end = endScreen,
                        strokeWidth = 6f * zoom,
                        cap = StrokeCap.Round
                    )
                }

                BoneId.UPPER_LEG_L, BoneId.UPPER_LEG_R -> {
                    val endX = matrix.transformX(0f, 16f)
                    val endY = matrix.transformY(0f, 16f)
                    val endScreen = worldToScreen(endX, endY)
                    drawScope.drawLine(
                        color = if (bone == BoneId.UPPER_LEG_R) baseColor else shadowColor,
                        start = screenPos,
                        end = endScreen,
                        strokeWidth = 8f * zoom,
                        cap = StrokeCap.Round
                    )
                }

                BoneId.LOWER_LEG_L, BoneId.LOWER_LEG_R -> {
                    val endX = matrix.transformX(0f, 14f)
                    val endY = matrix.transformY(0f, 14f)
                    val endScreen = worldToScreen(endX, endY)
                    drawScope.drawLine(
                        color = if (bone == BoneId.LOWER_LEG_R) Color(0xFF1E293B) else Color(0xFF0F172A),
                        start = screenPos,
                        end = endScreen,
                        strokeWidth = 7f * zoom,
                        cap = StrokeCap.Round
                    )
                }

                BoneId.WEAPON_R -> {
                    // Draw fighting game weapon (Blade / Energy Staff)
                    val tipX = matrix.transformX(0f, -34f)
                    val tipY = matrix.transformY(0f, -34f)
                    val tipScreen = worldToScreen(tipX, tipY)

                    // Glow blade line
                    drawScope.drawLine(
                        color = Color(0xFFFF4500),
                        start = screenPos,
                        end = tipScreen,
                        strokeWidth = 5f * zoom,
                        cap = StrokeCap.Round
                    )
                    // Core energy edge
                    drawScope.drawLine(
                        color = Color(0xFFFFF7ED),
                        start = screenPos,
                        end = tipScreen,
                        strokeWidth = 2f * zoom,
                        cap = StrokeCap.Round
                    )
                }

                else -> Unit
            }
        }

        // 3. Render Active Combat Hitboxes (for debugging & frame-perfect visual verification)
        for (h in activeHitboxes) {
            if (!h.isActive) continue
            val minPos = worldToScreen(h.worldBoundsMinX, h.worldBoundsMinY)
            val maxPos = worldToScreen(h.worldBoundsMaxX, h.worldBoundsMaxY)
            val hw = abs(maxPos.x - minPos.x)
            val hh = abs(maxPos.y - minPos.y)

            drawScope.drawRect(
                color = Color(0x66FF1744),
                topLeft = minPos,
                size = Size(hw, hh)
            )
            drawScope.drawRect(
                color = Color(0xFFFF1744),
                topLeft = minPos,
                size = Size(hw, hh),
                style = Stroke(width = 2f * zoom)
            )
        }
    }
}
